package velociraptor

import (
	"fmt"
	"os"
	"runtime"

	"gopkg.in/yaml.v3"
)

// APIConfig mirrors the fields Velociraptor's own `velociraptor config
// api_client` command writes to an api.config.yaml file (see
// api/proto/config.proto's ApiClientConfig message upstream). Field
// names match the real file's YAML keys exactly, so this project can
// load a config generated by a real Velociraptor server without any
// translation step.
//
// Every field here is either a secret (CACertificate, ClientCert,
// ClientPrivateKey) or effectively a secret-adjacent connection detail.
// APIConfig deliberately implements String/GoString so that any
// accidental fmt/log/error-wrapping of a value of this type (including
// through %v or %+v) can never print key material — see
// docs/security-model.md's secrets handling section.
type APIConfig struct {
	CACertificate       string `yaml:"ca_certificate"`
	ClientCert          string `yaml:"client_cert"`
	ClientPrivateKey    string `yaml:"client_private_key"`
	APIConnectionString string `yaml:"api_connection_string"`
	Name                string `yaml:"name"`

	// PinnedServerName overrides the TLS ServerName used to verify the
	// server's certificate. Velociraptor's own clients default to the
	// fixed name "VelociraptorServer" (see defaultPinnedServerName) when
	// this is empty, since Velociraptor's self-signed server certs are
	// issued for a fixed pinned name rather than a real DNS hostname.
	PinnedServerName string `yaml:"pinned_server_name"`

	// MaxGRPCRecvSize is accepted for forward compatibility with real
	// api.config.yaml files but is not yet applied to the gRPC dial
	// options in this milestone (no RPC that returns large payloads is
	// implemented yet). See the TODO in grpcclient.go.
	MaxGRPCRecvSize uint64 `yaml:"max_grpc_recv_size"`
}

// String and GoString are overridden so this type is safe to pass to
// any fmt/log/errors call by accident: it never prints ca_certificate,
// client_cert, or client_private_key contents, regardless of verb.
func (APIConfig) String() string   { return "velociraptor.APIConfig{REDACTED}" }
func (APIConfig) GoString() string { return "velociraptor.APIConfig{REDACTED}" }

// LoadAPIConfig reads and parses a Velociraptor api.config.yaml file at
// path, after checking that it is safe to read: it must exist, be a
// regular file, and (on POSIX platforms, where file mode bits are
// meaningful) be readable only by its owner. Returned errors include
// the file path (an operator-supplied, non-sensitive location) but
// never file contents.
func LoadAPIConfig(path string) (*APIConfig, error) {
	if path == "" {
		return nil, fmt.Errorf("velociraptor: api config path is empty")
	}

	info, err := os.Stat(path)
	if err != nil {
		return nil, fmt.Errorf("velociraptor: api config %s: %w", path, err)
	}
	if !info.Mode().IsRegular() {
		return nil, fmt.Errorf("velociraptor: api config %s: not a regular file", path)
	}

	// Private key material belongs in an owner-only-readable file, the
	// same convention as an SSH private key. This check is only
	// meaningful on POSIX platforms; Windows file mode bits don't carry
	// the same semantics and are skipped rather than producing a
	// permanently-failing check on that platform.
	if runtime.GOOS != "windows" {
		if perm := info.Mode().Perm(); perm&0o077 != 0 {
			return nil, fmt.Errorf(
				"velociraptor: api config %s: file mode %04o is too permissive (must not be readable/writable by group or other, e.g. chmod 0600)",
				path, perm)
		}
	}

	data, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("velociraptor: api config %s: %w", path, err)
	}

	var cfg APIConfig
	if err := yaml.Unmarshal(data, &cfg); err != nil {
		return nil, fmt.Errorf("velociraptor: api config %s: parse: %w", path, err)
	}

	var missing []string
	if cfg.CACertificate == "" {
		missing = append(missing, "ca_certificate")
	}
	if cfg.ClientCert == "" {
		missing = append(missing, "client_cert")
	}
	if cfg.ClientPrivateKey == "" {
		missing = append(missing, "client_private_key")
	}
	if cfg.APIConnectionString == "" {
		missing = append(missing, "api_connection_string")
	}
	if len(missing) > 0 {
		return nil, fmt.Errorf("velociraptor: api config %s: missing required field(s): %v", path, missing)
	}

	return &cfg, nil
}
