// Package approval defines the human-approval workflow that every
// endpoint-changing or evidence-disclosing operation must pass through:
// collections, hunts (start/cancel), flow cancellation, and upload
// download.
//
// The MCP server is not the security boundary by itself; approval is one
// of the MCP-layer controls that sit on top of Velociraptor-native ACLs.
// A tool that "requires approval" must refuse to call Velociraptor at
// all until a matching Decision with Approved=true exists for its
// Request.
//
// As of v0.4.0, a Request's ID is a human-chosen "approval reference"
// (e.g. a ticket number), not a value generated by this package: a human
// operator creates and decides a Request out-of-band via the
// agentic-velociraptor-mcp `approve` CLI subcommand (never an MCP tool,
// so no MCP client — including the LLM driving one — can create or
// decide its own approval), then hands the reference to whoever is
// running the MCP session. Every approval-gated MCP tool (v0.4.0's
// velo_collect_artifact_with_approval, velo_collect_dfir_profile_with_approval,
// velo_cancel_flow_with_approval, velo_download_flow_upload_with_approval;
// v0.6.0's velo_start_hunt_with_approval, velo_start_dfir_hunt_with_approval,
// velo_cancel_hunt_with_approval; v0.7.0's velo_hunt_ioc_with_approval)
// only ever calls Store.Get/IsApproved/Consume for a caller-supplied
// reference and always via verifyAndConsumeApproval's
// RequestFingerprint check; none of them can call Store.Create or
// Store.Decide. See docs/approval-flow.md for the full operator
// workflow.
package approval

import "time"

// Operation names a category of risky action. These strings are shared
// with config.PolicyConfig.RequireApprovalFor, so they must stay in
// sync; see internal/policy for the canonical list.
type Operation string

const (
	OperationCollectArtifact    Operation = "collect_artifact"
	OperationCollectDFIRProfile Operation = "collect_dfir_profile"
	OperationStartHunt          Operation = "start_hunt"
	OperationStartDFIRHunt      Operation = "start_dfir_hunt"
	OperationCancelFlow         Operation = "cancel_flow"
	OperationCancelHunt         Operation = "cancel_hunt"
	OperationDownloadFlowUpload Operation = "download_flow_upload"

	// OperationHuntIOC is velo_hunt_ioc_with_approval's operation
	// category: starting a hunt for one validated IOC (hash, IP, domain,
	// process, or path) via a fixed vql template, never raw VQL.
	OperationHuntIOC Operation = "hunt_ioc"
)

// Request captures everything needed for a human to make an informed
// approve/deny decision, and everything needed to audit that decision
// later. It intentionally requires a CaseID, Reason, and Requester:
// risky operations must be traceable to an investigation and to the
// identity that asked for them, not just to "the agent asked."
type Request struct {
	// ID is the approval reference: a human-chosen, opaque identifier
	// (e.g. a ticket number) unique within a Store. It is never
	// generated by this package and never by an MCP tool; see the
	// package doc comment.
	ID string `json:"id"`

	Operation Operation `json:"operation"`

	// CaseID ties this request to an investigation/case identifier.
	// Required: empty CaseID must be rejected by the approval store, not
	// silently accepted.
	CaseID string `json:"case_id"`

	// Reason is operator/agent-supplied justification for why this
	// operation is needed. Required, but not part of RequestFingerprint:
	// it is investigative context, not a targeting field.
	Reason string `json:"reason"`

	// Requester identifies who or what is asking for this operation
	// (e.g. an analyst's identity or an agent session label), distinct
	// from Decision.ApprovedBy, which identifies who authorized it.
	// Required, and never automatically equal to ApprovedBy: a Store
	// implementation must not let the same identity satisfy both roles
	// (see Decision's doc comment) — in practice this is enforced by
	// approval decisions only ever being made out-of-band via the
	// approve-collection CLI, never by any MCP tool.
	Requester string `json:"requester"`

	// ClientID / Artifact / Parameters / Profile / HuntID / FlowID /
	// UploadName describe the concrete target. Only the fields relevant
	// to Operation need be set.
	ClientID   string            `json:"client_id,omitempty"`
	Artifact   string            `json:"artifact,omitempty"`
	Parameters map[string]string `json:"parameters,omitempty"`
	Profile    string            `json:"profile,omitempty"`
	HuntID     string            `json:"hunt_id,omitempty"`
	FlowID     string            `json:"flow_id,omitempty"`
	UploadName string            `json:"upload_name,omitempty"`

	// ClientIDs / Label / TargetAll describe a hunt's multi-client scope
	// (OperationStartHunt, OperationStartDFIRHunt). Unlike ClientID
	// (single-client operations), a hunt approval must pin down exactly
	// which population it authorizes: an approval for "label=windows"
	// must not be replayable against "all clients".
	ClientIDs []string `json:"client_ids,omitempty"`
	Label     string   `json:"label,omitempty"`
	TargetAll bool     `json:"target_all,omitempty"`

	CreatedAt time.Time `json:"created_at"`
}

// Decision is the outcome of a Request, recorded independently of the
// request so that the audit trail shows who decided what and when.
//
// Decisions are produced exactly one way in this codebase: a human
// operator runs the agentic-velociraptor-mcp `approve` CLI subcommand
// against the same Store file the MCP server reads, identifying
// themselves via ApprovedBy. No MCP tool can construct or record a
// Decision, so the MCP client driving tool calls (including an LLM) can
// never self-approve its own Request.
type Decision struct {
	RequestID string `json:"request_id"`

	Approved bool `json:"approved"`

	// ApprovedBy identifies the human/system that made the decision.
	// Never the requesting agent/session; the approve CLI requires this
	// to be set explicitly by whoever runs it.
	ApprovedBy string `json:"approved_by"`

	DecidedAt time.Time `json:"decided_at"`

	// Note is an optional human note (denial reason, conditions, etc.).
	Note string `json:"note,omitempty"`
}
