// Copyright 2026 hdyrawan
//
// Minimal, hand-authored mirror of the subset of Velociraptor's
// `service API` (package `proto`, see api/proto/api.proto upstream)
// that this project calls: Check, ListClients, GetClient, and
// GetArtifacts. Because gRPC dispatches by fully-qualified method name
// (e.g. "/proto.API/ListClients"), this minimal service definition
// reaches the same server-side handlers as the upstream client would,
// without this project needing the other ~50 RPCs Velociraptor's API
// service exposes (hunts, collections, VFS, users, notebooks, the
// generic VQL Query RPC, ...), none of which this project's read-only
// visibility tools need or are permitted to use.
//
// Every RPC below is read-only against Velociraptor server-side state
// (it never launches a flow, hunt, or artifact collection). See
// docs/security-model.md and PROJECT_PLAN.md's v0.1.0 scope.
//
// Regenerate with (from the repository root):
//   buf generate internal/velociraptor/veloapi

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: api.proto

package veloapi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_api_proto protoreflect.FileDescriptor

const file_api_proto_rawDesc = "" +
	"\n" +
	"\tapi.proto\x12\x05proto\x1a\fhealth.proto\x1a\x10visibility.proto2\x8f\x02\n" +
	"\x03API\x12>\n" +
	"\x05Check\x12\x19.proto.HealthCheckRequest\x1a\x1a.proto.HealthCheckResponse\x12H\n" +
	"\vListClients\x12\x1b.proto.SearchClientsRequest\x1a\x1c.proto.SearchClientsResponse\x126\n" +
	"\tGetClient\x12\x17.proto.GetClientRequest\x1a\x10.proto.ApiClient\x12F\n" +
	"\fGetArtifacts\x12\x1a.proto.GetArtifactsRequest\x1a\x1a.proto.ArtifactDescriptorsBLZJgithub.com/hdyrawan/agentic-velociraptor-mcp/internal/velociraptor/veloapib\x06proto3"

var file_api_proto_goTypes = []any{
	(*HealthCheckRequest)(nil),    // 0: proto.HealthCheckRequest
	(*SearchClientsRequest)(nil),  // 1: proto.SearchClientsRequest
	(*GetClientRequest)(nil),      // 2: proto.GetClientRequest
	(*GetArtifactsRequest)(nil),   // 3: proto.GetArtifactsRequest
	(*HealthCheckResponse)(nil),   // 4: proto.HealthCheckResponse
	(*SearchClientsResponse)(nil), // 5: proto.SearchClientsResponse
	(*ApiClient)(nil),             // 6: proto.ApiClient
	(*ArtifactDescriptors)(nil),   // 7: proto.ArtifactDescriptors
}
var file_api_proto_depIdxs = []int32{
	0, // 0: proto.API.Check:input_type -> proto.HealthCheckRequest
	1, // 1: proto.API.ListClients:input_type -> proto.SearchClientsRequest
	2, // 2: proto.API.GetClient:input_type -> proto.GetClientRequest
	3, // 3: proto.API.GetArtifacts:input_type -> proto.GetArtifactsRequest
	4, // 4: proto.API.Check:output_type -> proto.HealthCheckResponse
	5, // 5: proto.API.ListClients:output_type -> proto.SearchClientsResponse
	6, // 6: proto.API.GetClient:output_type -> proto.ApiClient
	7, // 7: proto.API.GetArtifacts:output_type -> proto.ArtifactDescriptors
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_init() }
func file_api_proto_init() {
	if File_api_proto != nil {
		return
	}
	file_health_proto_init()
	file_visibility_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_rawDesc), len(file_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_goTypes,
		DependencyIndexes: file_api_proto_depIdxs,
	}.Build()
	File_api_proto = out.File
	file_api_proto_goTypes = nil
	file_api_proto_depIdxs = nil
}
