// Copyright 2026 hdyrawan
//
// Minimal mirror of flows/proto/artifact_collector.proto and
// api/proto/flows.proto: the subset of Velociraptor's flow-launching and
// flow-status messages this project's collection/cancel/flow-status
// tools need. Field names and numbers are copied from upstream so these
// messages stay wire-compatible with a real server.
//
// ArtifactCollectorArgs deliberately has no field carrying VQL text —
// artifacts are always referenced by name (Artifacts / ArtifactSpec.artifact)
// and parameters are always bound as VQLEnv key/value pairs
// (ArtifactParameters.env), never a raw query string. See
// docs/security-model.md.
//
// Regenerate with (from the repository root):
//   buf generate internal/velociraptor/veloapi

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: flows.proto

package veloapi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ArtifactCollectorContext_State int32

const (
	ArtifactCollectorContext_UNSET        ArtifactCollectorContext_State = 0
	ArtifactCollectorContext_RUNNING      ArtifactCollectorContext_State = 1
	ArtifactCollectorContext_FINISHED     ArtifactCollectorContext_State = 2
	ArtifactCollectorContext_ERROR        ArtifactCollectorContext_State = 3
	ArtifactCollectorContext_IN_PROGRESS  ArtifactCollectorContext_State = 4
	ArtifactCollectorContext_UNRESPONSIVE ArtifactCollectorContext_State = 5
	ArtifactCollectorContext_WAITING      ArtifactCollectorContext_State = 6
)

// Enum value maps for ArtifactCollectorContext_State.
var (
	ArtifactCollectorContext_State_name = map[int32]string{
		0: "UNSET",
		1: "RUNNING",
		2: "FINISHED",
		3: "ERROR",
		4: "IN_PROGRESS",
		5: "UNRESPONSIVE",
		6: "WAITING",
	}
	ArtifactCollectorContext_State_value = map[string]int32{
		"UNSET":        0,
		"RUNNING":      1,
		"FINISHED":     2,
		"ERROR":        3,
		"IN_PROGRESS":  4,
		"UNRESPONSIVE": 5,
		"WAITING":      6,
	}
)

func (x ArtifactCollectorContext_State) Enum() *ArtifactCollectorContext_State {
	p := new(ArtifactCollectorContext_State)
	*p = x
	return p
}

func (x ArtifactCollectorContext_State) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ArtifactCollectorContext_State) Descriptor() protoreflect.EnumDescriptor {
	return file_flows_proto_enumTypes[0].Descriptor()
}

func (ArtifactCollectorContext_State) Type() protoreflect.EnumType {
	return &file_flows_proto_enumTypes[0]
}

func (x ArtifactCollectorContext_State) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ArtifactCollectorContext_State.Descriptor instead.
func (ArtifactCollectorContext_State) EnumDescriptor() ([]byte, []int) {
	return file_flows_proto_rawDescGZIP(), []int{4, 0}
}

type ArtifactParameters struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Env           []*VQLEnv              `protobuf:"bytes,3,rep,name=env,proto3" json:"env,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArtifactParameters) Reset() {
	*x = ArtifactParameters{}
	mi := &file_flows_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArtifactParameters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArtifactParameters) ProtoMessage() {}

func (x *ArtifactParameters) ProtoReflect() protoreflect.Message {
	mi := &file_flows_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArtifactParameters.ProtoReflect.Descriptor instead.
func (*ArtifactParameters) Descriptor() ([]byte, []int) {
	return file_flows_proto_rawDescGZIP(), []int{0}
}

func (x *ArtifactParameters) GetEnv() []*VQLEnv {
	if x != nil {
		return x.Env
	}
	return nil
}

type ArtifactSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Artifact      string                 `protobuf:"bytes,1,opt,name=artifact,proto3" json:"artifact,omitempty"`
	Parameters    *ArtifactParameters    `protobuf:"bytes,2,opt,name=parameters,proto3" json:"parameters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArtifactSpec) Reset() {
	*x = ArtifactSpec{}
	mi := &file_flows_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArtifactSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArtifactSpec) ProtoMessage() {}

func (x *ArtifactSpec) ProtoReflect() protoreflect.Message {
	mi := &file_flows_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArtifactSpec.ProtoReflect.Descriptor instead.
func (*ArtifactSpec) Descriptor() ([]byte, []int) {
	return file_flows_proto_rawDescGZIP(), []int{1}
}

func (x *ArtifactSpec) GetArtifact() string {
	if x != nil {
		return x.Artifact
	}
	return ""
}

func (x *ArtifactSpec) GetParameters() *ArtifactParameters {
	if x != nil {
		return x.Parameters
	}
	return nil
}

type ArtifactCollectorArgs struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Creator  string                 `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	ClientId string                 `protobuf:"bytes,3,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	FlowId   string                 `protobuf:"bytes,31,opt,name=flow_id,json=flowId,proto3" json:"flow_id,omitempty"`
	// Old-style artifact list (no per-artifact parameters).
	Artifacts []string `protobuf:"bytes,2,rep,name=artifacts,proto3" json:"artifacts,omitempty"`
	// New-style artifact list, each with its own bound parameters. This
	// project always uses specs (never the bare artifacts list above) so
	// every collection/hunt carries explicit, fixed parameter bindings.
	Specs          []*ArtifactSpec `protobuf:"bytes,24,rep,name=specs,proto3" json:"specs,omitempty"`
	Timeout        uint64          `protobuf:"varint,7,opt,name=timeout,proto3" json:"timeout,omitempty"`
	MaxRows        uint64          `protobuf:"varint,22,opt,name=max_rows,json=maxRows,proto3" json:"max_rows,omitempty"`
	MaxUploadBytes uint64          `protobuf:"varint,23,opt,name=max_upload_bytes,json=maxUploadBytes,proto3" json:"max_upload_bytes,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ArtifactCollectorArgs) Reset() {
	*x = ArtifactCollectorArgs{}
	mi := &file_flows_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArtifactCollectorArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArtifactCollectorArgs) ProtoMessage() {}

func (x *ArtifactCollectorArgs) ProtoReflect() protoreflect.Message {
	mi := &file_flows_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArtifactCollectorArgs.ProtoReflect.Descriptor instead.
func (*ArtifactCollectorArgs) Descriptor() ([]byte, []int) {
	return file_flows_proto_rawDescGZIP(), []int{2}
}

func (x *ArtifactCollectorArgs) GetCreator() string {
	if x != nil {
		return x.Creator
	}
	return ""
}

func (x *ArtifactCollectorArgs) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *ArtifactCollectorArgs) GetFlowId() string {
	if x != nil {
		return x.FlowId
	}
	return ""
}

func (x *ArtifactCollectorArgs) GetArtifacts() []string {
	if x != nil {
		return x.Artifacts
	}
	return nil
}

func (x *ArtifactCollectorArgs) GetSpecs() []*ArtifactSpec {
	if x != nil {
		return x.Specs
	}
	return nil
}

func (x *ArtifactCollectorArgs) GetTimeout() uint64 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

func (x *ArtifactCollectorArgs) GetMaxRows() uint64 {
	if x != nil {
		return x.MaxRows
	}
	return 0
}

func (x *ArtifactCollectorArgs) GetMaxUploadBytes() uint64 {
	if x != nil {
		return x.MaxUploadBytes
	}
	return 0
}

type ArtifactCollectorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FlowId        string                 `protobuf:"bytes,1,opt,name=flow_id,json=flowId,proto3" json:"flow_id,omitempty"`
	Request       *ArtifactCollectorArgs `protobuf:"bytes,2,opt,name=request,proto3" json:"request,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArtifactCollectorResponse) Reset() {
	*x = ArtifactCollectorResponse{}
	mi := &file_flows_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArtifactCollectorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArtifactCollectorResponse) ProtoMessage() {}

func (x *ArtifactCollectorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_flows_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArtifactCollectorResponse.ProtoReflect.Descriptor instead.
func (*ArtifactCollectorResponse) Descriptor() ([]byte, []int) {
	return file_flows_proto_rawDescGZIP(), []int{3}
}

func (x *ArtifactCollectorResponse) GetFlowId() string {
	if x != nil {
		return x.FlowId
	}
	return ""
}

func (x *ArtifactCollectorResponse) GetRequest() *ArtifactCollectorArgs {
	if x != nil {
		return x.Request
	}
	return nil
}

// ArtifactCollectorContext deliberately omits every field this project's
// flow-status tool does not read (backtraces, per-query stats, previous
// flow history, ...); see FlowDetails.
type ArtifactCollectorContext struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ClientId           string                 `protobuf:"bytes,27,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	SessionId          string                 `protobuf:"bytes,13,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Request            *ArtifactCollectorArgs `protobuf:"bytes,11,opt,name=request,proto3" json:"request,omitempty"`
	CreateTime         uint64                 `protobuf:"varint,3,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	ActiveTime         uint64                 `protobuf:"varint,17,opt,name=active_time,json=activeTime,proto3" json:"active_time,omitempty"`
	TotalCollectedRows uint64                 `protobuf:"varint,28,opt,name=total_collected_rows,json=totalCollectedRows,proto3" json:"total_collected_rows,omitempty"`
	TotalUploadedBytes uint64                 `protobuf:"varint,26,opt,name=total_uploaded_bytes,json=totalUploadedBytes,proto3" json:"total_uploaded_bytes,omitempty"`
	// Contents of an error/cancellation status string sent by the client
	// or set by CancelFlow ("Cancelled by <user>: ..."). Used to
	// distinguish a genuinely errored flow from an operator-cancelled one,
	// since Velociraptor's real State enum below has no separate
	// "cancelled" value — cancellation is ERROR plus this status prefix.
	Status        string                         `protobuf:"bytes,15,opt,name=status,proto3" json:"status,omitempty"`
	State         ArtifactCollectorContext_State `protobuf:"varint,14,opt,name=state,proto3,enum=proto.ArtifactCollectorContext_State" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArtifactCollectorContext) Reset() {
	*x = ArtifactCollectorContext{}
	mi := &file_flows_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArtifactCollectorContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArtifactCollectorContext) ProtoMessage() {}

func (x *ArtifactCollectorContext) ProtoReflect() protoreflect.Message {
	mi := &file_flows_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArtifactCollectorContext.ProtoReflect.Descriptor instead.
func (*ArtifactCollectorContext) Descriptor() ([]byte, []int) {
	return file_flows_proto_rawDescGZIP(), []int{4}
}

func (x *ArtifactCollectorContext) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *ArtifactCollectorContext) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ArtifactCollectorContext) GetRequest() *ArtifactCollectorArgs {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *ArtifactCollectorContext) GetCreateTime() uint64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *ArtifactCollectorContext) GetActiveTime() uint64 {
	if x != nil {
		return x.ActiveTime
	}
	return 0
}

func (x *ArtifactCollectorContext) GetTotalCollectedRows() uint64 {
	if x != nil {
		return x.TotalCollectedRows
	}
	return 0
}

func (x *ArtifactCollectorContext) GetTotalUploadedBytes() uint64 {
	if x != nil {
		return x.TotalUploadedBytes
	}
	return 0
}

func (x *ArtifactCollectorContext) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ArtifactCollectorContext) GetState() ArtifactCollectorContext_State {
	if x != nil {
		return x.State
	}
	return ArtifactCollectorContext_UNSET
}

type FlowDetails struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Context       *ArtifactCollectorContext `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlowDetails) Reset() {
	*x = FlowDetails{}
	mi := &file_flows_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlowDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlowDetails) ProtoMessage() {}

func (x *FlowDetails) ProtoReflect() protoreflect.Message {
	mi := &file_flows_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlowDetails.ProtoReflect.Descriptor instead.
func (*FlowDetails) Descriptor() ([]byte, []int) {
	return file_flows_proto_rawDescGZIP(), []int{5}
}

func (x *FlowDetails) GetContext() *ArtifactCollectorContext {
	if x != nil {
		return x.Context
	}
	return nil
}

type ApiFlowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	FlowId        string                 `protobuf:"bytes,2,opt,name=flow_id,json=flowId,proto3" json:"flow_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiFlowRequest) Reset() {
	*x = ApiFlowRequest{}
	mi := &file_flows_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiFlowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiFlowRequest) ProtoMessage() {}

func (x *ApiFlowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_flows_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiFlowRequest.ProtoReflect.Descriptor instead.
func (*ApiFlowRequest) Descriptor() ([]byte, []int) {
	return file_flows_proto_rawDescGZIP(), []int{6}
}

func (x *ApiFlowRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *ApiFlowRequest) GetFlowId() string {
	if x != nil {
		return x.FlowId
	}
	return ""
}

type StartFlowResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FlowId        string                 `protobuf:"bytes,1,opt,name=flow_id,json=flowId,proto3" json:"flow_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartFlowResponse) Reset() {
	*x = StartFlowResponse{}
	mi := &file_flows_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartFlowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartFlowResponse) ProtoMessage() {}

func (x *StartFlowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_flows_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartFlowResponse.ProtoReflect.Descriptor instead.
func (*StartFlowResponse) Descriptor() ([]byte, []int) {
	return file_flows_proto_rawDescGZIP(), []int{7}
}

func (x *StartFlowResponse) GetFlowId() string {
	if x != nil {
		return x.FlowId
	}
	return ""
}

var File_flows_proto protoreflect.FileDescriptor

const file_flows_proto_rawDesc = "" +
	"\n" +
	"\vflows.proto\x12\x05proto\x1a\tvql.proto\"5\n" +
	"\x12ArtifactParameters\x12\x1f\n" +
	"\x03env\x18\x03 \x03(\v2\r.proto.VQLEnvR\x03env\"e\n" +
	"\fArtifactSpec\x12\x1a\n" +
	"\bartifact\x18\x01 \x01(\tR\bartifact\x129\n" +
	"\n" +
	"parameters\x18\x02 \x01(\v2\x19.proto.ArtifactParametersR\n" +
	"parameters\"\x8f\x02\n" +
	"\x15ArtifactCollectorArgs\x12\x18\n" +
	"\acreator\x18\x01 \x01(\tR\acreator\x12\x1b\n" +
	"\tclient_id\x18\x03 \x01(\tR\bclientId\x12\x17\n" +
	"\aflow_id\x18\x1f \x01(\tR\x06flowId\x12\x1c\n" +
	"\tartifacts\x18\x02 \x03(\tR\tartifacts\x12)\n" +
	"\x05specs\x18\x18 \x03(\v2\x13.proto.ArtifactSpecR\x05specs\x12\x18\n" +
	"\atimeout\x18\a \x01(\x04R\atimeout\x12\x19\n" +
	"\bmax_rows\x18\x16 \x01(\x04R\amaxRows\x12(\n" +
	"\x10max_upload_bytes\x18\x17 \x01(\x04R\x0emaxUploadBytes\"l\n" +
	"\x19ArtifactCollectorResponse\x12\x17\n" +
	"\aflow_id\x18\x01 \x01(\tR\x06flowId\x126\n" +
	"\arequest\x18\x02 \x01(\v2\x1c.proto.ArtifactCollectorArgsR\arequest\"\xf3\x03\n" +
	"\x18ArtifactCollectorContext\x12\x1b\n" +
	"\tclient_id\x18\x1b \x01(\tR\bclientId\x12\x1d\n" +
	"\n" +
	"session_id\x18\r \x01(\tR\tsessionId\x126\n" +
	"\arequest\x18\v \x01(\v2\x1c.proto.ArtifactCollectorArgsR\arequest\x12\x1f\n" +
	"\vcreate_time\x18\x03 \x01(\x04R\n" +
	"createTime\x12\x1f\n" +
	"\vactive_time\x18\x11 \x01(\x04R\n" +
	"activeTime\x120\n" +
	"\x14total_collected_rows\x18\x1c \x01(\x04R\x12totalCollectedRows\x120\n" +
	"\x14total_uploaded_bytes\x18\x1a \x01(\x04R\x12totalUploadedBytes\x12\x16\n" +
	"\x06status\x18\x0f \x01(\tR\x06status\x12;\n" +
	"\x05state\x18\x0e \x01(\x0e2%.proto.ArtifactCollectorContext.StateR\x05state\"h\n" +
	"\x05State\x12\t\n" +
	"\x05UNSET\x10\x00\x12\v\n" +
	"\aRUNNING\x10\x01\x12\f\n" +
	"\bFINISHED\x10\x02\x12\t\n" +
	"\x05ERROR\x10\x03\x12\x0f\n" +
	"\vIN_PROGRESS\x10\x04\x12\x10\n" +
	"\fUNRESPONSIVE\x10\x05\x12\v\n" +
	"\aWAITING\x10\x06\"H\n" +
	"\vFlowDetails\x129\n" +
	"\acontext\x18\x01 \x01(\v2\x1f.proto.ArtifactCollectorContextR\acontext\"F\n" +
	"\x0eApiFlowRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12\x17\n" +
	"\aflow_id\x18\x02 \x01(\tR\x06flowId\",\n" +
	"\x11StartFlowResponse\x12\x17\n" +
	"\aflow_id\x18\x01 \x01(\tR\x06flowIdBLZJgithub.com/hdyrawan/agentic-velociraptor-mcp/internal/velociraptor/veloapib\x06proto3"

var (
	file_flows_proto_rawDescOnce sync.Once
	file_flows_proto_rawDescData []byte
)

func file_flows_proto_rawDescGZIP() []byte {
	file_flows_proto_rawDescOnce.Do(func() {
		file_flows_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_flows_proto_rawDesc), len(file_flows_proto_rawDesc)))
	})
	return file_flows_proto_rawDescData
}

var file_flows_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_flows_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_flows_proto_goTypes = []any{
	(ArtifactCollectorContext_State)(0), // 0: proto.ArtifactCollectorContext.State
	(*ArtifactParameters)(nil),          // 1: proto.ArtifactParameters
	(*ArtifactSpec)(nil),                // 2: proto.ArtifactSpec
	(*ArtifactCollectorArgs)(nil),       // 3: proto.ArtifactCollectorArgs
	(*ArtifactCollectorResponse)(nil),   // 4: proto.ArtifactCollectorResponse
	(*ArtifactCollectorContext)(nil),    // 5: proto.ArtifactCollectorContext
	(*FlowDetails)(nil),                 // 6: proto.FlowDetails
	(*ApiFlowRequest)(nil),              // 7: proto.ApiFlowRequest
	(*StartFlowResponse)(nil),           // 8: proto.StartFlowResponse
	(*VQLEnv)(nil),                      // 9: proto.VQLEnv
}
var file_flows_proto_depIdxs = []int32{
	9, // 0: proto.ArtifactParameters.env:type_name -> proto.VQLEnv
	1, // 1: proto.ArtifactSpec.parameters:type_name -> proto.ArtifactParameters
	2, // 2: proto.ArtifactCollectorArgs.specs:type_name -> proto.ArtifactSpec
	3, // 3: proto.ArtifactCollectorResponse.request:type_name -> proto.ArtifactCollectorArgs
	3, // 4: proto.ArtifactCollectorContext.request:type_name -> proto.ArtifactCollectorArgs
	0, // 5: proto.ArtifactCollectorContext.state:type_name -> proto.ArtifactCollectorContext.State
	5, // 6: proto.FlowDetails.context:type_name -> proto.ArtifactCollectorContext
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_flows_proto_init() }
func file_flows_proto_init() {
	if File_flows_proto != nil {
		return
	}
	file_vql_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_flows_proto_rawDesc), len(file_flows_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_flows_proto_goTypes,
		DependencyIndexes: file_flows_proto_depIdxs,
		EnumInfos:         file_flows_proto_enumTypes,
		MessageInfos:      file_flows_proto_msgTypes,
	}.Build()
	File_flows_proto = out.File
	file_flows_proto_goTypes = nil
	file_flows_proto_depIdxs = nil
}
