// Copyright 2026 hdyrawan
//
// Minimal, hand-authored mirror of the single gRPC method this project
// calls on a Velociraptor server: API.Check (a health check, modeled on
// the standard gRPC health-checking protocol). Field names, numbers,
// and the package/service names below are copied from the upstream
// Velociraptor project's own proto definitions so that this message
// is wire-compatible with a real `www.velocidex.com/golang/velociraptor`
// server:
//
//   - api/proto/health.proto (HealthCheckRequest, HealthCheckResponse)
//   - api/proto/api.proto (`service API { rpc Check(...) ... }`)
//   - api/health.go (server-side handler: ignores the request entirely
//     and returns SERVING unconditionally once a call authenticates)
//
// This project deliberately does NOT import the upstream
// Velocidex/velociraptor Go module (it is a full DFIR server, not a thin
// client library, and pulls in a large, unrelated dependency tree). This
// file instead defines only the one RPC this project actually calls, so
// the generated client stub is small, auditable, and has no other
// capability. No VQL execution, collection, hunt, or other RPC is
// defined here — see docs/security-model.md and PROJECT_PLAN.md for why
// those remain out of scope.
//
// Regenerate with (from the repository root):
//   buf generate internal/velociraptor/veloapi

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: health.proto

package veloapi

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	API_Check_FullMethodName = "/proto.API/Check"
)

// APIClient is the client API for API service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// API mirrors the subset of Velociraptor's `service API` (package
// `proto`, see api/proto/api.proto upstream) that this project calls:
// Check only. Because gRPC dispatches by the fully-qualified method
// name "/proto.API/Check", this minimal service definition reaches the
// same server-side handler as the upstream client would, without this
// project needing the other ~30 RPCs Velociraptor's API service
// exposes (hunts, collections, VFS, users, ...), none of which this
// project's read-only health check needs or is permitted to use.
type APIClient interface {
	Check(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
}

type aPIClient struct {
	cc grpc.ClientConnInterface
}

func NewAPIClient(cc grpc.ClientConnInterface) APIClient {
	return &aPIClient{cc}
}

func (c *aPIClient) Check(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, API_Check_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// APIServer is the server API for API service.
// All implementations must embed UnimplementedAPIServer
// for forward compatibility.
//
// API mirrors the subset of Velociraptor's `service API` (package
// `proto`, see api/proto/api.proto upstream) that this project calls:
// Check only. Because gRPC dispatches by the fully-qualified method
// name "/proto.API/Check", this minimal service definition reaches the
// same server-side handler as the upstream client would, without this
// project needing the other ~30 RPCs Velociraptor's API service
// exposes (hunts, collections, VFS, users, ...), none of which this
// project's read-only health check needs or is permitted to use.
type APIServer interface {
	Check(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	mustEmbedUnimplementedAPIServer()
}

// UnimplementedAPIServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAPIServer struct{}

func (UnimplementedAPIServer) Check(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Check not implemented")
}
func (UnimplementedAPIServer) mustEmbedUnimplementedAPIServer() {}
func (UnimplementedAPIServer) testEmbeddedByValue()             {}

// UnsafeAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to APIServer will
// result in compilation errors.
type UnsafeAPIServer interface {
	mustEmbedUnimplementedAPIServer()
}

func RegisterAPIServer(s grpc.ServiceRegistrar, srv APIServer) {
	// If the following call panics, it indicates UnimplementedAPIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&API_ServiceDesc, srv)
}

func _API_Check_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).Check(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: API_Check_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).Check(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// API_ServiceDesc is the grpc.ServiceDesc for API service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var API_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.API",
	HandlerType: (*APIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Check",
			Handler:    _API_Check_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "health.proto",
}
