// Copyright 2026 hdyrawan
//
// Minimal mirror of api/proto/hunts.proto: the subset of Velociraptor's
// hunt messages this project's hunt management tools need. Field names
// and numbers are copied from upstream so these messages stay
// wire-compatible with a real server.
//
// HuntCondition deliberately has only two real targeting modes: a set of
// labels (HuntLabelCondition) or an operating system
// (HuntOsCondition) — the same two modes upstream Velociraptor itself
// supports for a hunt's condition. There is no field anywhere in
// Velociraptor's hunt proto for "this explicit list of client IDs"; a
// hunt can only be scoped by label, by OS, or left unset (all clients).
// See docs/security-model.md's hunt-scope section for what this means
// for this project's client_ids hunt-scope input.
//
// Regenerate with (from the repository root):
//   buf generate internal/velociraptor/veloapi

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: hunts.proto

package veloapi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HuntOsCondition_OS int32

const (
	HuntOsCondition_ALL     HuntOsCondition_OS = 0
	HuntOsCondition_WINDOWS HuntOsCondition_OS = 1
	HuntOsCondition_LINUX   HuntOsCondition_OS = 2
	HuntOsCondition_OSX     HuntOsCondition_OS = 3
)

// Enum value maps for HuntOsCondition_OS.
var (
	HuntOsCondition_OS_name = map[int32]string{
		0: "ALL",
		1: "WINDOWS",
		2: "LINUX",
		3: "OSX",
	}
	HuntOsCondition_OS_value = map[string]int32{
		"ALL":     0,
		"WINDOWS": 1,
		"LINUX":   2,
		"OSX":     3,
	}
)

func (x HuntOsCondition_OS) Enum() *HuntOsCondition_OS {
	p := new(HuntOsCondition_OS)
	*p = x
	return p
}

func (x HuntOsCondition_OS) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HuntOsCondition_OS) Descriptor() protoreflect.EnumDescriptor {
	return file_hunts_proto_enumTypes[0].Descriptor()
}

func (HuntOsCondition_OS) Type() protoreflect.EnumType {
	return &file_hunts_proto_enumTypes[0]
}

func (x HuntOsCondition_OS) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HuntOsCondition_OS.Descriptor instead.
func (HuntOsCondition_OS) EnumDescriptor() ([]byte, []int) {
	return file_hunts_proto_rawDescGZIP(), []int{1, 0}
}

type Hunt_State int32

const (
	Hunt_UNSET    Hunt_State = 0
	Hunt_PAUSED   Hunt_State = 1
	Hunt_RUNNING  Hunt_State = 2
	Hunt_STOPPED  Hunt_State = 3
	Hunt_ARCHIVED Hunt_State = 4
	Hunt_DELETED  Hunt_State = 5
)

// Enum value maps for Hunt_State.
var (
	Hunt_State_name = map[int32]string{
		0: "UNSET",
		1: "PAUSED",
		2: "RUNNING",
		3: "STOPPED",
		4: "ARCHIVED",
		5: "DELETED",
	}
	Hunt_State_value = map[string]int32{
		"UNSET":    0,
		"PAUSED":   1,
		"RUNNING":  2,
		"STOPPED":  3,
		"ARCHIVED": 4,
		"DELETED":  5,
	}
)

func (x Hunt_State) Enum() *Hunt_State {
	p := new(Hunt_State)
	*p = x
	return p
}

func (x Hunt_State) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Hunt_State) Descriptor() protoreflect.EnumDescriptor {
	return file_hunts_proto_enumTypes[1].Descriptor()
}

func (Hunt_State) Type() protoreflect.EnumType {
	return &file_hunts_proto_enumTypes[1]
}

func (x Hunt_State) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Hunt_State.Descriptor instead.
func (Hunt_State) EnumDescriptor() ([]byte, []int) {
	return file_hunts_proto_rawDescGZIP(), []int{4, 0}
}

type HuntLabelCondition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Label         []string               `protobuf:"bytes,1,rep,name=label,proto3" json:"label,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HuntLabelCondition) Reset() {
	*x = HuntLabelCondition{}
	mi := &file_hunts_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HuntLabelCondition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HuntLabelCondition) ProtoMessage() {}

func (x *HuntLabelCondition) ProtoReflect() protoreflect.Message {
	mi := &file_hunts_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HuntLabelCondition.ProtoReflect.Descriptor instead.
func (*HuntLabelCondition) Descriptor() ([]byte, []int) {
	return file_hunts_proto_rawDescGZIP(), []int{0}
}

func (x *HuntLabelCondition) GetLabel() []string {
	if x != nil {
		return x.Label
	}
	return nil
}

type HuntOsCondition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Os            HuntOsCondition_OS     `protobuf:"varint,1,opt,name=os,proto3,enum=proto.HuntOsCondition_OS" json:"os,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HuntOsCondition) Reset() {
	*x = HuntOsCondition{}
	mi := &file_hunts_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HuntOsCondition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HuntOsCondition) ProtoMessage() {}

func (x *HuntOsCondition) ProtoReflect() protoreflect.Message {
	mi := &file_hunts_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HuntOsCondition.ProtoReflect.Descriptor instead.
func (*HuntOsCondition) Descriptor() ([]byte, []int) {
	return file_hunts_proto_rawDescGZIP(), []int{1}
}

func (x *HuntOsCondition) GetOs() HuntOsCondition_OS {
	if x != nil {
		return x.Os
	}
	return HuntOsCondition_ALL
}

type HuntCondition struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ExcludedLabels *HuntLabelCondition    `protobuf:"bytes,4,opt,name=excluded_labels,json=excludedLabels,proto3" json:"excluded_labels,omitempty"`
	// Types that are valid to be assigned to UnionField:
	//
	//	*HuntCondition_Labels
	//	*HuntCondition_Os
	UnionField    isHuntCondition_UnionField `protobuf_oneof:"union_field"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HuntCondition) Reset() {
	*x = HuntCondition{}
	mi := &file_hunts_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HuntCondition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HuntCondition) ProtoMessage() {}

func (x *HuntCondition) ProtoReflect() protoreflect.Message {
	mi := &file_hunts_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HuntCondition.ProtoReflect.Descriptor instead.
func (*HuntCondition) Descriptor() ([]byte, []int) {
	return file_hunts_proto_rawDescGZIP(), []int{2}
}

func (x *HuntCondition) GetExcludedLabels() *HuntLabelCondition {
	if x != nil {
		return x.ExcludedLabels
	}
	return nil
}

func (x *HuntCondition) GetUnionField() isHuntCondition_UnionField {
	if x != nil {
		return x.UnionField
	}
	return nil
}

func (x *HuntCondition) GetLabels() *HuntLabelCondition {
	if x != nil {
		if x, ok := x.UnionField.(*HuntCondition_Labels); ok {
			return x.Labels
		}
	}
	return nil
}

func (x *HuntCondition) GetOs() *HuntOsCondition {
	if x != nil {
		if x, ok := x.UnionField.(*HuntCondition_Os); ok {
			return x.Os
		}
	}
	return nil
}

type isHuntCondition_UnionField interface {
	isHuntCondition_UnionField()
}

type HuntCondition_Labels struct {
	Labels *HuntLabelCondition `protobuf:"bytes,2,opt,name=labels,proto3,oneof"`
}

type HuntCondition_Os struct {
	Os *HuntOsCondition `protobuf:"bytes,3,opt,name=os,proto3,oneof"`
}

func (*HuntCondition_Labels) isHuntCondition_UnionField() {}

func (*HuntCondition_Os) isHuntCondition_UnionField() {}

// HuntStats deliberately omits every stat this project doesn't surface
// (upload/row counters, download links, ...); EstimateHunt only ever
// populates total_clients_scheduled.
type HuntStats struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	TotalClientsScheduled uint64                 `protobuf:"varint,9,opt,name=total_clients_scheduled,json=totalClientsScheduled,proto3" json:"total_clients_scheduled,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *HuntStats) Reset() {
	*x = HuntStats{}
	mi := &file_hunts_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HuntStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HuntStats) ProtoMessage() {}

func (x *HuntStats) ProtoReflect() protoreflect.Message {
	mi := &file_hunts_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HuntStats.ProtoReflect.Descriptor instead.
func (*HuntStats) Descriptor() ([]byte, []int) {
	return file_hunts_proto_rawDescGZIP(), []int{3}
}

func (x *HuntStats) GetTotalClientsScheduled() uint64 {
	if x != nil {
		return x.TotalClientsScheduled
	}
	return 0
}

type Hunt struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	HuntId          string                 `protobuf:"bytes,1,opt,name=hunt_id,json=huntId,proto3" json:"hunt_id,omitempty"`
	CreateTime      uint64                 `protobuf:"varint,2,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	Creator         string                 `protobuf:"bytes,12,opt,name=creator,proto3" json:"creator,omitempty"`
	StartTime       uint64                 `protobuf:"varint,21,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	HuntDescription string                 `protobuf:"bytes,11,opt,name=hunt_description,json=huntDescription,proto3" json:"hunt_description,omitempty"`
	StartRequest    *ArtifactCollectorArgs `protobuf:"bytes,16,opt,name=start_request,json=startRequest,proto3" json:"start_request,omitempty"`
	Condition       *HuntCondition         `protobuf:"bytes,4,opt,name=condition,proto3" json:"condition,omitempty"`
	ClientLimit     uint64                 `protobuf:"varint,6,opt,name=client_limit,json=clientLimit,proto3" json:"client_limit,omitempty"`
	Stats           *HuntStats             `protobuf:"bytes,18,opt,name=stats,proto3" json:"stats,omitempty"`
	Artifacts       []string               `protobuf:"bytes,17,rep,name=artifacts,proto3" json:"artifacts,omitempty"`
	State           Hunt_State             `protobuf:"varint,8,opt,name=state,proto3,enum=proto.Hunt_State" json:"state,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Hunt) Reset() {
	*x = Hunt{}
	mi := &file_hunts_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hunt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hunt) ProtoMessage() {}

func (x *Hunt) ProtoReflect() protoreflect.Message {
	mi := &file_hunts_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hunt.ProtoReflect.Descriptor instead.
func (*Hunt) Descriptor() ([]byte, []int) {
	return file_hunts_proto_rawDescGZIP(), []int{4}
}

func (x *Hunt) GetHuntId() string {
	if x != nil {
		return x.HuntId
	}
	return ""
}

func (x *Hunt) GetCreateTime() uint64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *Hunt) GetCreator() string {
	if x != nil {
		return x.Creator
	}
	return ""
}

func (x *Hunt) GetStartTime() uint64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *Hunt) GetHuntDescription() string {
	if x != nil {
		return x.HuntDescription
	}
	return ""
}

func (x *Hunt) GetStartRequest() *ArtifactCollectorArgs {
	if x != nil {
		return x.StartRequest
	}
	return nil
}

func (x *Hunt) GetCondition() *HuntCondition {
	if x != nil {
		return x.Condition
	}
	return nil
}

func (x *Hunt) GetClientLimit() uint64 {
	if x != nil {
		return x.ClientLimit
	}
	return 0
}

func (x *Hunt) GetStats() *HuntStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

func (x *Hunt) GetArtifacts() []string {
	if x != nil {
		return x.Artifacts
	}
	return nil
}

func (x *Hunt) GetState() Hunt_State {
	if x != nil {
		return x.State
	}
	return Hunt_UNSET
}

type HuntEstimateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LastActive    uint64                 `protobuf:"varint,1,opt,name=last_active,json=lastActive,proto3" json:"last_active,omitempty"`
	Condition     *HuntCondition         `protobuf:"bytes,4,opt,name=condition,proto3" json:"condition,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HuntEstimateRequest) Reset() {
	*x = HuntEstimateRequest{}
	mi := &file_hunts_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HuntEstimateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HuntEstimateRequest) ProtoMessage() {}

func (x *HuntEstimateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hunts_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HuntEstimateRequest.ProtoReflect.Descriptor instead.
func (*HuntEstimateRequest) Descriptor() ([]byte, []int) {
	return file_hunts_proto_rawDescGZIP(), []int{5}
}

func (x *HuntEstimateRequest) GetLastActive() uint64 {
	if x != nil {
		return x.LastActive
	}
	return 0
}

func (x *HuntEstimateRequest) GetCondition() *HuntCondition {
	if x != nil {
		return x.Condition
	}
	return nil
}

type ListHuntsRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Offset          uint64                 `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Count           uint64                 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	IncludeArchived bool                   `protobuf:"varint,3,opt,name=include_archived,json=includeArchived,proto3" json:"include_archived,omitempty"`
	Summary         bool                   `protobuf:"varint,4,opt,name=summary,proto3" json:"summary,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ListHuntsRequest) Reset() {
	*x = ListHuntsRequest{}
	mi := &file_hunts_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListHuntsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListHuntsRequest) ProtoMessage() {}

func (x *ListHuntsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hunts_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListHuntsRequest.ProtoReflect.Descriptor instead.
func (*ListHuntsRequest) Descriptor() ([]byte, []int) {
	return file_hunts_proto_rawDescGZIP(), []int{6}
}

func (x *ListHuntsRequest) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListHuntsRequest) GetCount() uint64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *ListHuntsRequest) GetIncludeArchived() bool {
	if x != nil {
		return x.IncludeArchived
	}
	return false
}

func (x *ListHuntsRequest) GetSummary() bool {
	if x != nil {
		return x.Summary
	}
	return false
}

type ListHuntsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Hunt                `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListHuntsResponse) Reset() {
	*x = ListHuntsResponse{}
	mi := &file_hunts_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListHuntsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListHuntsResponse) ProtoMessage() {}

func (x *ListHuntsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hunts_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListHuntsResponse.ProtoReflect.Descriptor instead.
func (*ListHuntsResponse) Descriptor() ([]byte, []int) {
	return file_hunts_proto_rawDescGZIP(), []int{7}
}

func (x *ListHuntsResponse) GetItems() []*Hunt {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListHuntsResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type GetHuntRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HuntId        string                 `protobuf:"bytes,1,opt,name=hunt_id,json=huntId,proto3" json:"hunt_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHuntRequest) Reset() {
	*x = GetHuntRequest{}
	mi := &file_hunts_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHuntRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHuntRequest) ProtoMessage() {}

func (x *GetHuntRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hunts_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHuntRequest.ProtoReflect.Descriptor instead.
func (*GetHuntRequest) Descriptor() ([]byte, []int) {
	return file_hunts_proto_rawDescGZIP(), []int{8}
}

func (x *GetHuntRequest) GetHuntId() string {
	if x != nil {
		return x.HuntId
	}
	return ""
}

type GetHuntResultsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Offset        uint64                 `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Count         uint64                 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	HuntId        string                 `protobuf:"bytes,3,opt,name=hunt_id,json=huntId,proto3" json:"hunt_id,omitempty"`
	Artifact      string                 `protobuf:"bytes,4,opt,name=artifact,proto3" json:"artifact,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHuntResultsRequest) Reset() {
	*x = GetHuntResultsRequest{}
	mi := &file_hunts_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHuntResultsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHuntResultsRequest) ProtoMessage() {}

func (x *GetHuntResultsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hunts_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHuntResultsRequest.ProtoReflect.Descriptor instead.
func (*GetHuntResultsRequest) Descriptor() ([]byte, []int) {
	return file_hunts_proto_rawDescGZIP(), []int{9}
}

func (x *GetHuntResultsRequest) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *GetHuntResultsRequest) GetCount() uint64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *GetHuntResultsRequest) GetHuntId() string {
	if x != nil {
		return x.HuntId
	}
	return ""
}

func (x *GetHuntResultsRequest) GetArtifact() string {
	if x != nil {
		return x.Artifact
	}
	return ""
}

// HuntMutation deliberately exposes only hunt_id/state/user: this
// project only ever uses ModifyHunt to stop a hunt
// (state = Hunt.State.STOPPED), never to change its description, tags,
// expiry, or assign an existing flow to it.
type HuntMutation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HuntId        string                 `protobuf:"bytes,1,opt,name=hunt_id,json=huntId,proto3" json:"hunt_id,omitempty"`
	State         Hunt_State             `protobuf:"varint,4,opt,name=state,proto3,enum=proto.Hunt_State" json:"state,omitempty"`
	User          string                 `protobuf:"bytes,9,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HuntMutation) Reset() {
	*x = HuntMutation{}
	mi := &file_hunts_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HuntMutation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HuntMutation) ProtoMessage() {}

func (x *HuntMutation) ProtoReflect() protoreflect.Message {
	mi := &file_hunts_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HuntMutation.ProtoReflect.Descriptor instead.
func (*HuntMutation) Descriptor() ([]byte, []int) {
	return file_hunts_proto_rawDescGZIP(), []int{10}
}

func (x *HuntMutation) GetHuntId() string {
	if x != nil {
		return x.HuntId
	}
	return ""
}

func (x *HuntMutation) GetState() Hunt_State {
	if x != nil {
		return x.State
	}
	return Hunt_UNSET
}

func (x *HuntMutation) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

var File_hunts_proto protoreflect.FileDescriptor

const file_hunts_proto_rawDesc = "" +
	"\n" +
	"\vhunts.proto\x12\x05proto\x1a\vflows.proto\"*\n" +
	"\x12HuntLabelCondition\x12\x14\n" +
	"\x05label\x18\x01 \x03(\tR\x05label\"l\n" +
	"\x0fHuntOsCondition\x12)\n" +
	"\x02os\x18\x01 \x01(\x0e2\x19.proto.HuntOsCondition.OSR\x02os\".\n" +
	"\x02OS\x12\a\n" +
	"\x03ALL\x10\x00\x12\v\n" +
	"\aWINDOWS\x10\x01\x12\t\n" +
	"\x05LINUX\x10\x02\x12\a\n" +
	"\x03OSX\x10\x03\"\xc1\x01\n" +
	"\rHuntCondition\x12B\n" +
	"\x0fexcluded_labels\x18\x04 \x01(\v2\x19.proto.HuntLabelConditionR\x0eexcludedLabels\x123\n" +
	"\x06labels\x18\x02 \x01(\v2\x19.proto.HuntLabelConditionH\x00R\x06labels\x12(\n" +
	"\x02os\x18\x03 \x01(\v2\x16.proto.HuntOsConditionH\x00R\x02osB\r\n" +
	"\vunion_field\"C\n" +
	"\tHuntStats\x126\n" +
	"\x17total_clients_scheduled\x18\t \x01(\x04R\x15totalClientsScheduled\"\x82\x04\n" +
	"\x04Hunt\x12\x17\n" +
	"\ahunt_id\x18\x01 \x01(\tR\x06huntId\x12\x1f\n" +
	"\vcreate_time\x18\x02 \x01(\x04R\n" +
	"createTime\x12\x18\n" +
	"\acreator\x18\f \x01(\tR\acreator\x12\x1d\n" +
	"\n" +
	"start_time\x18\x15 \x01(\x04R\tstartTime\x12)\n" +
	"\x10hunt_description\x18\v \x01(\tR\x0fhuntDescription\x12A\n" +
	"\rstart_request\x18\x10 \x01(\v2\x1c.proto.ArtifactCollectorArgsR\fstartRequest\x122\n" +
	"\tcondition\x18\x04 \x01(\v2\x14.proto.HuntConditionR\tcondition\x12!\n" +
	"\fclient_limit\x18\x06 \x01(\x04R\vclientLimit\x12&\n" +
	"\x05stats\x18\x12 \x01(\v2\x10.proto.HuntStatsR\x05stats\x12\x1c\n" +
	"\tartifacts\x18\x11 \x03(\tR\tartifacts\x12'\n" +
	"\x05state\x18\b \x01(\x0e2\x11.proto.Hunt.StateR\x05state\"S\n" +
	"\x05State\x12\t\n" +
	"\x05UNSET\x10\x00\x12\n" +
	"\n" +
	"\x06PAUSED\x10\x01\x12\v\n" +
	"\aRUNNING\x10\x02\x12\v\n" +
	"\aSTOPPED\x10\x03\x12\f\n" +
	"\bARCHIVED\x10\x04\x12\v\n" +
	"\aDELETED\x10\x05\"j\n" +
	"\x13HuntEstimateRequest\x12\x1f\n" +
	"\vlast_active\x18\x01 \x01(\x04R\n" +
	"lastActive\x122\n" +
	"\tcondition\x18\x04 \x01(\v2\x14.proto.HuntConditionR\tcondition\"\x85\x01\n" +
	"\x10ListHuntsRequest\x12\x16\n" +
	"\x06offset\x18\x01 \x01(\x04R\x06offset\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x04R\x05count\x12)\n" +
	"\x10include_archived\x18\x03 \x01(\bR\x0fincludeArchived\x12\x18\n" +
	"\asummary\x18\x04 \x01(\bR\asummary\"L\n" +
	"\x11ListHuntsResponse\x12!\n" +
	"\x05items\x18\x01 \x03(\v2\v.proto.HuntR\x05items\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\")\n" +
	"\x0eGetHuntRequest\x12\x17\n" +
	"\ahunt_id\x18\x01 \x01(\tR\x06huntId\"z\n" +
	"\x15GetHuntResultsRequest\x12\x16\n" +
	"\x06offset\x18\x01 \x01(\x04R\x06offset\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x04R\x05count\x12\x17\n" +
	"\ahunt_id\x18\x03 \x01(\tR\x06huntId\x12\x1a\n" +
	"\bartifact\x18\x04 \x01(\tR\bartifact\"d\n" +
	"\fHuntMutation\x12\x17\n" +
	"\ahunt_id\x18\x01 \x01(\tR\x06huntId\x12'\n" +
	"\x05state\x18\x04 \x01(\x0e2\x11.proto.Hunt.StateR\x05state\x12\x12\n" +
	"\x04user\x18\t \x01(\tR\x04userBLZJgithub.com/hdyrawan/agentic-velociraptor-mcp/internal/velociraptor/veloapib\x06proto3"

var (
	file_hunts_proto_rawDescOnce sync.Once
	file_hunts_proto_rawDescData []byte
)

func file_hunts_proto_rawDescGZIP() []byte {
	file_hunts_proto_rawDescOnce.Do(func() {
		file_hunts_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_hunts_proto_rawDesc), len(file_hunts_proto_rawDesc)))
	})
	return file_hunts_proto_rawDescData
}

var file_hunts_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_hunts_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_hunts_proto_goTypes = []any{
	(HuntOsCondition_OS)(0),       // 0: proto.HuntOsCondition.OS
	(Hunt_State)(0),               // 1: proto.Hunt.State
	(*HuntLabelCondition)(nil),    // 2: proto.HuntLabelCondition
	(*HuntOsCondition)(nil),       // 3: proto.HuntOsCondition
	(*HuntCondition)(nil),         // 4: proto.HuntCondition
	(*HuntStats)(nil),             // 5: proto.HuntStats
	(*Hunt)(nil),                  // 6: proto.Hunt
	(*HuntEstimateRequest)(nil),   // 7: proto.HuntEstimateRequest
	(*ListHuntsRequest)(nil),      // 8: proto.ListHuntsRequest
	(*ListHuntsResponse)(nil),     // 9: proto.ListHuntsResponse
	(*GetHuntRequest)(nil),        // 10: proto.GetHuntRequest
	(*GetHuntResultsRequest)(nil), // 11: proto.GetHuntResultsRequest
	(*HuntMutation)(nil),          // 12: proto.HuntMutation
	(*ArtifactCollectorArgs)(nil), // 13: proto.ArtifactCollectorArgs
}
var file_hunts_proto_depIdxs = []int32{
	0,  // 0: proto.HuntOsCondition.os:type_name -> proto.HuntOsCondition.OS
	2,  // 1: proto.HuntCondition.excluded_labels:type_name -> proto.HuntLabelCondition
	2,  // 2: proto.HuntCondition.labels:type_name -> proto.HuntLabelCondition
	3,  // 3: proto.HuntCondition.os:type_name -> proto.HuntOsCondition
	13, // 4: proto.Hunt.start_request:type_name -> proto.ArtifactCollectorArgs
	4,  // 5: proto.Hunt.condition:type_name -> proto.HuntCondition
	5,  // 6: proto.Hunt.stats:type_name -> proto.HuntStats
	1,  // 7: proto.Hunt.state:type_name -> proto.Hunt.State
	4,  // 8: proto.HuntEstimateRequest.condition:type_name -> proto.HuntCondition
	6,  // 9: proto.ListHuntsResponse.items:type_name -> proto.Hunt
	1,  // 10: proto.HuntMutation.state:type_name -> proto.Hunt.State
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_hunts_proto_init() }
func file_hunts_proto_init() {
	if File_hunts_proto != nil {
		return
	}
	file_flows_proto_init()
	file_hunts_proto_msgTypes[2].OneofWrappers = []any{
		(*HuntCondition_Labels)(nil),
		(*HuntCondition_Os)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_hunts_proto_rawDesc), len(file_hunts_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_hunts_proto_goTypes,
		DependencyIndexes: file_hunts_proto_depIdxs,
		EnumInfos:         file_hunts_proto_enumTypes,
		MessageInfos:      file_hunts_proto_msgTypes,
	}.Build()
	File_hunts_proto = out.File
	file_hunts_proto_goTypes = nil
	file_hunts_proto_depIdxs = nil
}
