// Copyright 2026 hdyrawan
//
// Minimal mirror of api/proto/csv.proto's GetTableRequest/Row/
// GetTableResponse messages, wire-compatible with a real Velociraptor
// server (field names/numbers copied from upstream). Velociraptor's
// GetTable/GetClientFlows/GetHuntFlows/GetHuntResults RPCs all return
// GetTableResponse: a fixed column-name list plus one JSON-encoded
// array per row (Row.json). This project decodes those rows generically
// by zipping GetTableResponse.columns against each row's JSON array —
// never by parsing or constructing VQL text; the row shape is whatever
// columns the artifact/RPC declares, and both flow/hunt results and
// upload metadata reuse the same decoder (see
// internal/velociraptor/table.go).
//
// GetTableRequest.type selects which table a request reads (Velociraptor
// server-side concern, not this project's): "" for an artifact's own
// collected rows, "uploads" for a flow's upload metadata, "clients"/
// "hunt_status" for hunt tables. This project only ever sets Type to one
// of these fixed literals, never a caller-supplied string.
//
// Regenerate with (from the repository root):
//   buf generate internal/velociraptor/veloapi

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: table.proto

package veloapi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetTableRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Rows     uint64                 `protobuf:"varint,2,opt,name=rows,proto3" json:"rows,omitempty"`
	StartRow uint64                 `protobuf:"varint,3,opt,name=start_row,json=startRow,proto3" json:"start_row,omitempty"`
	ClientId string                 `protobuf:"bytes,4,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	FlowId   string                 `protobuf:"bytes,5,opt,name=flow_id,json=flowId,proto3" json:"flow_id,omitempty"`
	Artifact string                 `protobuf:"bytes,6,opt,name=artifact,proto3" json:"artifact,omitempty"`
	// Can be "uploads" for a flow's upload metadata table; empty for the
	// artifact's own collected rows.
	Type          string `protobuf:"bytes,7,opt,name=type,proto3" json:"type,omitempty"`
	HuntId        string `protobuf:"bytes,8,opt,name=hunt_id,json=huntId,proto3" json:"hunt_id,omitempty"`
	SortColumn    string `protobuf:"bytes,19,opt,name=sort_column,json=sortColumn,proto3" json:"sort_column,omitempty"`
	SortDirection bool   `protobuf:"varint,20,opt,name=sort_direction,json=sortDirection,proto3" json:"sort_direction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTableRequest) Reset() {
	*x = GetTableRequest{}
	mi := &file_table_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTableRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTableRequest) ProtoMessage() {}

func (x *GetTableRequest) ProtoReflect() protoreflect.Message {
	mi := &file_table_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTableRequest.ProtoReflect.Descriptor instead.
func (*GetTableRequest) Descriptor() ([]byte, []int) {
	return file_table_proto_rawDescGZIP(), []int{0}
}

func (x *GetTableRequest) GetRows() uint64 {
	if x != nil {
		return x.Rows
	}
	return 0
}

func (x *GetTableRequest) GetStartRow() uint64 {
	if x != nil {
		return x.StartRow
	}
	return 0
}

func (x *GetTableRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *GetTableRequest) GetFlowId() string {
	if x != nil {
		return x.FlowId
	}
	return ""
}

func (x *GetTableRequest) GetArtifact() string {
	if x != nil {
		return x.Artifact
	}
	return ""
}

func (x *GetTableRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *GetTableRequest) GetHuntId() string {
	if x != nil {
		return x.HuntId
	}
	return ""
}

func (x *GetTableRequest) GetSortColumn() string {
	if x != nil {
		return x.SortColumn
	}
	return ""
}

func (x *GetTableRequest) GetSortDirection() bool {
	if x != nil {
		return x.SortDirection
	}
	return false
}

type Row struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The row encoded as a JSON array: the entire JSON []interface{}
	// serialized into a single JSON string, positionally matching
	// GetTableResponse.columns.
	Json          string `protobuf:"bytes,2,opt,name=json,proto3" json:"json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Row) Reset() {
	*x = Row{}
	mi := &file_table_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Row) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Row) ProtoMessage() {}

func (x *Row) ProtoReflect() protoreflect.Message {
	mi := &file_table_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Row.ProtoReflect.Descriptor instead.
func (*Row) Descriptor() ([]byte, []int) {
	return file_table_proto_rawDescGZIP(), []int{1}
}

func (x *Row) GetJson() string {
	if x != nil {
		return x.Json
	}
	return ""
}

type GetTableResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Columns       []string               `protobuf:"bytes,1,rep,name=columns,proto3" json:"columns,omitempty"`
	Rows          []*Row                 `protobuf:"bytes,2,rep,name=rows,proto3" json:"rows,omitempty"`
	TotalRows     int64                  `protobuf:"varint,3,opt,name=total_rows,json=totalRows,proto3" json:"total_rows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTableResponse) Reset() {
	*x = GetTableResponse{}
	mi := &file_table_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTableResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTableResponse) ProtoMessage() {}

func (x *GetTableResponse) ProtoReflect() protoreflect.Message {
	mi := &file_table_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTableResponse.ProtoReflect.Descriptor instead.
func (*GetTableResponse) Descriptor() ([]byte, []int) {
	return file_table_proto_rawDescGZIP(), []int{2}
}

func (x *GetTableResponse) GetColumns() []string {
	if x != nil {
		return x.Columns
	}
	return nil
}

func (x *GetTableResponse) GetRows() []*Row {
	if x != nil {
		return x.Rows
	}
	return nil
}

func (x *GetTableResponse) GetTotalRows() int64 {
	if x != nil {
		return x.TotalRows
	}
	return 0
}

var File_table_proto protoreflect.FileDescriptor

const file_table_proto_rawDesc = "" +
	"\n" +
	"\vtable.proto\x12\x05proto\"\x89\x02\n" +
	"\x0fGetTableRequest\x12\x12\n" +
	"\x04rows\x18\x02 \x01(\x04R\x04rows\x12\x1b\n" +
	"\tstart_row\x18\x03 \x01(\x04R\bstartRow\x12\x1b\n" +
	"\tclient_id\x18\x04 \x01(\tR\bclientId\x12\x17\n" +
	"\aflow_id\x18\x05 \x01(\tR\x06flowId\x12\x1a\n" +
	"\bartifact\x18\x06 \x01(\tR\bartifact\x12\x12\n" +
	"\x04type\x18\a \x01(\tR\x04type\x12\x17\n" +
	"\ahunt_id\x18\b \x01(\tR\x06huntId\x12\x1f\n" +
	"\vsort_column\x18\x13 \x01(\tR\n" +
	"sortColumn\x12%\n" +
	"\x0esort_direction\x18\x14 \x01(\bR\rsortDirection\"\x19\n" +
	"\x03Row\x12\x12\n" +
	"\x04json\x18\x02 \x01(\tR\x04json\"k\n" +
	"\x10GetTableResponse\x12\x18\n" +
	"\acolumns\x18\x01 \x03(\tR\acolumns\x12\x1e\n" +
	"\x04rows\x18\x02 \x03(\v2\n" +
	".proto.RowR\x04rows\x12\x1d\n" +
	"\n" +
	"total_rows\x18\x03 \x01(\x03R\ttotalRowsBLZJgithub.com/hdyrawan/agentic-velociraptor-mcp/internal/velociraptor/veloapib\x06proto3"

var (
	file_table_proto_rawDescOnce sync.Once
	file_table_proto_rawDescData []byte
)

func file_table_proto_rawDescGZIP() []byte {
	file_table_proto_rawDescOnce.Do(func() {
		file_table_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_table_proto_rawDesc), len(file_table_proto_rawDesc)))
	})
	return file_table_proto_rawDescData
}

var file_table_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_table_proto_goTypes = []any{
	(*GetTableRequest)(nil),  // 0: proto.GetTableRequest
	(*Row)(nil),              // 1: proto.Row
	(*GetTableResponse)(nil), // 2: proto.GetTableResponse
}
var file_table_proto_depIdxs = []int32{
	1, // 0: proto.GetTableResponse.rows:type_name -> proto.Row
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_table_proto_init() }
func file_table_proto_init() {
	if File_table_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_table_proto_rawDesc), len(file_table_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_table_proto_goTypes,
		DependencyIndexes: file_table_proto_depIdxs,
		MessageInfos:      file_table_proto_msgTypes,
	}.Build()
	File_table_proto = out.File
	file_table_proto_goTypes = nil
	file_table_proto_depIdxs = nil
}
