// Copyright 2026 hdyrawan
//
// Minimal mirror of api/proto/api.proto's VFSFileBuffer message, used
// only through the VFSGetBuffer RPC: "This can be used by API clients to
// fetch file content" (upstream's own doc comment on VFSGetBuffer,
// distinguishing it from the GUI's separate HTTP-only download
// handlers). This is the one typed, chunked, offset/length-bounded RPC
// Velociraptor exposes over gRPC for reading already-collected file
// bytes by client_id + file-store components — the mechanism
// velo_download_flow_upload_with_approval uses, never a raw filesystem
// or HTTP path.
//
// Regenerate with (from the repository root):
//   buf generate internal/velociraptor/veloapi

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: vfs.proto

package veloapi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VFSFileBuffer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Offset        uint64                 `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	Length        uint32                 `protobuf:"varint,4,opt,name=length,proto3" json:"length,omitempty"`
	Data          []byte                 `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
	Components    []string               `protobuf:"bytes,6,rep,name=components,proto3" json:"components,omitempty"`
	Padding       *bool                  `protobuf:"varint,8,opt,name=padding,proto3,oneof" json:"padding,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VFSFileBuffer) Reset() {
	*x = VFSFileBuffer{}
	mi := &file_vfs_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VFSFileBuffer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VFSFileBuffer) ProtoMessage() {}

func (x *VFSFileBuffer) ProtoReflect() protoreflect.Message {
	mi := &file_vfs_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VFSFileBuffer.ProtoReflect.Descriptor instead.
func (*VFSFileBuffer) Descriptor() ([]byte, []int) {
	return file_vfs_proto_rawDescGZIP(), []int{0}
}

func (x *VFSFileBuffer) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *VFSFileBuffer) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *VFSFileBuffer) GetLength() uint32 {
	if x != nil {
		return x.Length
	}
	return 0
}

func (x *VFSFileBuffer) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *VFSFileBuffer) GetComponents() []string {
	if x != nil {
		return x.Components
	}
	return nil
}

func (x *VFSFileBuffer) GetPadding() bool {
	if x != nil && x.Padding != nil {
		return *x.Padding
	}
	return false
}

var File_vfs_proto protoreflect.FileDescriptor

const file_vfs_proto_rawDesc = "" +
	"\n" +
	"\tvfs.proto\x12\x05proto\"\xbb\x01\n" +
	"\rVFSFileBuffer\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x04R\x06offset\x12\x16\n" +
	"\x06length\x18\x04 \x01(\rR\x06length\x12\x12\n" +
	"\x04data\x18\x05 \x01(\fR\x04data\x12\x1e\n" +
	"\n" +
	"components\x18\x06 \x03(\tR\n" +
	"components\x12\x1d\n" +
	"\apadding\x18\b \x01(\bH\x00R\apadding\x88\x01\x01B\n" +
	"\n" +
	"\b_paddingBLZJgithub.com/hdyrawan/agentic-velociraptor-mcp/internal/velociraptor/veloapib\x06proto3"

var (
	file_vfs_proto_rawDescOnce sync.Once
	file_vfs_proto_rawDescData []byte
)

func file_vfs_proto_rawDescGZIP() []byte {
	file_vfs_proto_rawDescOnce.Do(func() {
		file_vfs_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_vfs_proto_rawDesc), len(file_vfs_proto_rawDesc)))
	})
	return file_vfs_proto_rawDescData
}

var file_vfs_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_vfs_proto_goTypes = []any{
	(*VFSFileBuffer)(nil), // 0: proto.VFSFileBuffer
}
var file_vfs_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_vfs_proto_init() }
func file_vfs_proto_init() {
	if File_vfs_proto != nil {
		return
	}
	file_vfs_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_vfs_proto_rawDesc), len(file_vfs_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_vfs_proto_goTypes,
		DependencyIndexes: file_vfs_proto_depIdxs,
		MessageInfos:      file_vfs_proto_msgTypes,
	}.Build()
	File_vfs_proto = out.File
	file_vfs_proto_goTypes = nil
	file_vfs_proto_depIdxs = nil
}
