// Copyright 2026 hdyrawan
//
// Minimal, hand-authored mirror of the Velociraptor client-search and
// artifact-catalog messages used by the v0.1.0 read-only visibility
// tools (velo_search_clients, velo_get_client_info,
// velo_list_artifact_names, velo_get_artifact_details). Field names and
// numbers are copied from the upstream Velociraptor project's own proto
// definitions so these messages are wire-compatible with a real
// `www.velocidex.com/golang/velociraptor` server:
//
//   - api/proto/clients.proto (SearchClientsRequest,
//     SearchClientsResponse, GetClientRequest, ApiClient,
//     AgentInformation, Uname)
//   - artifacts/proto/artifact.proto (Artifact, ArtifactParameter,
//     ArtifactSource)
//   - api/proto/artifacts.proto (GetArtifactsRequest, ArtifactDescriptors)
//
// Each message here is intentionally a narrow subset of its upstream
// counterpart: only the fields these tools actually read are declared.
// Fields are omitted by field number, not renumbered, so the wire
// format still matches upstream exactly. As of v0.10.3, `Artifact`
// declares `sources` (field 4) as a minimal `ArtifactSource` carrying
// only `name` (field 3) — needed to resolve a multi-source artifact's
// result table (internal/velociraptor/grpcclient_flows.go's
// GetFlowResults) — but every field carrying an actual VQL query body
// (`ArtifactSource.query`/`queries`/`precondition`) remains
// permanently undeclared: a server populating those fields simply
// arrives as an ignored unknown field — this project's generated Go
// types have no field to decode them into, so artifact VQL text can
// never reach a tool response even by accident. See
// docs/security-model.md.
//
// Regenerate with (from the repository root):
//   buf generate internal/velociraptor/veloapi

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: visibility.proto

package veloapi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SearchClientsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Offset        uint64                 `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit         uint64                 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Query         string                 `protobuf:"bytes,3,opt,name=query,proto3" json:"query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchClientsRequest) Reset() {
	*x = SearchClientsRequest{}
	mi := &file_visibility_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchClientsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchClientsRequest) ProtoMessage() {}

func (x *SearchClientsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_visibility_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchClientsRequest.ProtoReflect.Descriptor instead.
func (*SearchClientsRequest) Descriptor() ([]byte, []int) {
	return file_visibility_proto_rawDescGZIP(), []int{0}
}

func (x *SearchClientsRequest) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *SearchClientsRequest) GetLimit() uint64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *SearchClientsRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

type SearchClientsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*ApiClient           `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Total         uint64                 `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchClientsResponse) Reset() {
	*x = SearchClientsResponse{}
	mi := &file_visibility_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchClientsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchClientsResponse) ProtoMessage() {}

func (x *SearchClientsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_visibility_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchClientsResponse.ProtoReflect.Descriptor instead.
func (*SearchClientsResponse) Descriptor() ([]byte, []int) {
	return file_visibility_proto_rawDescGZIP(), []int{1}
}

func (x *SearchClientsResponse) GetItems() []*ApiClient {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *SearchClientsResponse) GetTotal() uint64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type GetClientRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetClientRequest) Reset() {
	*x = GetClientRequest{}
	mi := &file_visibility_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClientRequest) ProtoMessage() {}

func (x *GetClientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_visibility_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClientRequest.ProtoReflect.Descriptor instead.
func (*GetClientRequest) Descriptor() ([]byte, []int) {
	return file_visibility_proto_rawDescGZIP(), []int{2}
}

func (x *GetClientRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

type AgentInformation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentInformation) Reset() {
	*x = AgentInformation{}
	mi := &file_visibility_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentInformation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentInformation) ProtoMessage() {}

func (x *AgentInformation) ProtoReflect() protoreflect.Message {
	mi := &file_visibility_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentInformation.ProtoReflect.Descriptor instead.
func (*AgentInformation) Descriptor() ([]byte, []int) {
	return file_visibility_proto_rawDescGZIP(), []int{3}
}

func (x *AgentInformation) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type Uname struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	System        string                 `protobuf:"bytes,1,opt,name=system,proto3" json:"system,omitempty"`
	Hostname      string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	MacAddresses  []string               `protobuf:"bytes,11,rep,name=mac_addresses,json=macAddresses,proto3" json:"mac_addresses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Uname) Reset() {
	*x = Uname{}
	mi := &file_visibility_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Uname) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Uname) ProtoMessage() {}

func (x *Uname) ProtoReflect() protoreflect.Message {
	mi := &file_visibility_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Uname.ProtoReflect.Descriptor instead.
func (*Uname) Descriptor() ([]byte, []int) {
	return file_visibility_proto_rawDescGZIP(), []int{4}
}

func (x *Uname) GetSystem() string {
	if x != nil {
		return x.System
	}
	return ""
}

func (x *Uname) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *Uname) GetMacAddresses() []string {
	if x != nil {
		return x.MacAddresses
	}
	return nil
}

// ApiClient deliberately omits every field describing GUI/approval
// state, VFS state, or in-flight flow bookkeeping: velo_search_clients
// and velo_get_client_info return endpoint identity/metadata only.
type ApiClient struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ClientId         string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	AgentInformation *AgentInformation      `protobuf:"bytes,2,opt,name=agent_information,json=agentInformation,proto3" json:"agent_information,omitempty"`
	OsInfo           *Uname                 `protobuf:"bytes,3,opt,name=os_info,json=osInfo,proto3" json:"os_info,omitempty"`
	LastSeenAt       uint64                 `protobuf:"varint,7,opt,name=last_seen_at,json=lastSeenAt,proto3" json:"last_seen_at,omitempty"`
	LastIp           string                 `protobuf:"bytes,16,opt,name=last_ip,json=lastIp,proto3" json:"last_ip,omitempty"`
	Labels           []string               `protobuf:"bytes,18,rep,name=labels,proto3" json:"labels,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ApiClient) Reset() {
	*x = ApiClient{}
	mi := &file_visibility_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiClient) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiClient) ProtoMessage() {}

func (x *ApiClient) ProtoReflect() protoreflect.Message {
	mi := &file_visibility_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiClient.ProtoReflect.Descriptor instead.
func (*ApiClient) Descriptor() ([]byte, []int) {
	return file_visibility_proto_rawDescGZIP(), []int{5}
}

func (x *ApiClient) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *ApiClient) GetAgentInformation() *AgentInformation {
	if x != nil {
		return x.AgentInformation
	}
	return nil
}

func (x *ApiClient) GetOsInfo() *Uname {
	if x != nil {
		return x.OsInfo
	}
	return nil
}

func (x *ApiClient) GetLastSeenAt() uint64 {
	if x != nil {
		return x.LastSeenAt
	}
	return 0
}

func (x *ApiClient) GetLastIp() string {
	if x != nil {
		return x.LastIp
	}
	return ""
}

func (x *ApiClient) GetLabels() []string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type ArtifactParameter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Default       string                 `protobuf:"bytes,2,opt,name=default,proto3" json:"default,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArtifactParameter) Reset() {
	*x = ArtifactParameter{}
	mi := &file_visibility_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArtifactParameter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArtifactParameter) ProtoMessage() {}

func (x *ArtifactParameter) ProtoReflect() protoreflect.Message {
	mi := &file_visibility_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArtifactParameter.ProtoReflect.Descriptor instead.
func (*ArtifactParameter) Descriptor() ([]byte, []int) {
	return file_visibility_proto_rawDescGZIP(), []int{6}
}

func (x *ArtifactParameter) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ArtifactParameter) GetDefault() string {
	if x != nil {
		return x.Default
	}
	return ""
}

func (x *ArtifactParameter) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ArtifactParameter) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

// ArtifactSource mirrors upstream's artifacts/proto/artifact.proto
// ArtifactSource message, declaring only `name` (field 3) — the field
// this project needs to resolve a named-source artifact's per-source
// result table (see internal/velociraptor/grpcclient_flows.go's
// GetFlowResults doc comment). Every other field on the real message
// (`precondition`, `queries`, `query` — the actual VQL body — and
// `notebook`) is deliberately omitted so this project's generated Go
// types have no field to decode VQL text into, even if a real server's
// response carries it.
type ArtifactSource struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArtifactSource) Reset() {
	*x = ArtifactSource{}
	mi := &file_visibility_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArtifactSource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArtifactSource) ProtoMessage() {}

func (x *ArtifactSource) ProtoReflect() protoreflect.Message {
	mi := &file_visibility_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArtifactSource.ProtoReflect.Descriptor instead.
func (*ArtifactSource) Descriptor() ([]byte, []int) {
	return file_visibility_proto_rawDescGZIP(), []int{7}
}

func (x *ArtifactSource) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// Artifact declares `sources` (field 4, matching upstream's field
// number exactly) as `ArtifactSource` — source *names* only, never a
// query body (see ArtifactSource above). Every other field carrying VQL
// text, tool definitions, or precondition expressions remains omitted:
// this project's artifact catalog tools return name/description/
// parameter/source-name metadata only, never a VQL body.
type Artifact struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Parameters    []*ArtifactParameter   `protobuf:"bytes,3,rep,name=parameters,proto3" json:"parameters,omitempty"`
	Sources       []*ArtifactSource      `protobuf:"bytes,4,rep,name=sources,proto3" json:"sources,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Artifact) Reset() {
	*x = Artifact{}
	mi := &file_visibility_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Artifact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Artifact) ProtoMessage() {}

func (x *Artifact) ProtoReflect() protoreflect.Message {
	mi := &file_visibility_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Artifact.ProtoReflect.Descriptor instead.
func (*Artifact) Descriptor() ([]byte, []int) {
	return file_visibility_proto_rawDescGZIP(), []int{8}
}

func (x *Artifact) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Artifact) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Artifact) GetParameters() []*ArtifactParameter {
	if x != nil {
		return x.Parameters
	}
	return nil
}

func (x *Artifact) GetSources() []*ArtifactSource {
	if x != nil {
		return x.Sources
	}
	return nil
}

type GetArtifactsRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SearchTerm      string                 `protobuf:"bytes,3,opt,name=search_term,json=searchTerm,proto3" json:"search_term,omitempty"`
	NumberOfResults uint64                 `protobuf:"varint,4,opt,name=number_of_results,json=numberOfResults,proto3" json:"number_of_results,omitempty"`
	Names           []string               `protobuf:"bytes,6,rep,name=names,proto3" json:"names,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetArtifactsRequest) Reset() {
	*x = GetArtifactsRequest{}
	mi := &file_visibility_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetArtifactsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetArtifactsRequest) ProtoMessage() {}

func (x *GetArtifactsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_visibility_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetArtifactsRequest.ProtoReflect.Descriptor instead.
func (*GetArtifactsRequest) Descriptor() ([]byte, []int) {
	return file_visibility_proto_rawDescGZIP(), []int{9}
}

func (x *GetArtifactsRequest) GetSearchTerm() string {
	if x != nil {
		return x.SearchTerm
	}
	return ""
}

func (x *GetArtifactsRequest) GetNumberOfResults() uint64 {
	if x != nil {
		return x.NumberOfResults
	}
	return 0
}

func (x *GetArtifactsRequest) GetNames() []string {
	if x != nil {
		return x.Names
	}
	return nil
}

type ArtifactDescriptors struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Artifact            `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArtifactDescriptors) Reset() {
	*x = ArtifactDescriptors{}
	mi := &file_visibility_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArtifactDescriptors) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArtifactDescriptors) ProtoMessage() {}

func (x *ArtifactDescriptors) ProtoReflect() protoreflect.Message {
	mi := &file_visibility_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArtifactDescriptors.ProtoReflect.Descriptor instead.
func (*ArtifactDescriptors) Descriptor() ([]byte, []int) {
	return file_visibility_proto_rawDescGZIP(), []int{10}
}

func (x *ArtifactDescriptors) GetItems() []*Artifact {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_visibility_proto protoreflect.FileDescriptor

const file_visibility_proto_rawDesc = "" +
	"\n" +
	"\x10visibility.proto\x12\x05proto\"Z\n" +
	"\x14SearchClientsRequest\x12\x16\n" +
	"\x06offset\x18\x01 \x01(\x04R\x06offset\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x04R\x05limit\x12\x14\n" +
	"\x05query\x18\x03 \x01(\tR\x05query\"U\n" +
	"\x15SearchClientsResponse\x12&\n" +
	"\x05items\x18\x01 \x03(\v2\x10.proto.ApiClientR\x05items\x12\x14\n" +
	"\x05total\x18\x03 \x01(\x04R\x05total\"/\n" +
	"\x10GetClientRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\",\n" +
	"\x10AgentInformation\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\"`\n" +
	"\x05Uname\x12\x16\n" +
	"\x06system\x18\x01 \x01(\tR\x06system\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12#\n" +
	"\rmac_addresses\x18\v \x03(\tR\fmacAddresses\"\xe8\x01\n" +
	"\tApiClient\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12D\n" +
	"\x11agent_information\x18\x02 \x01(\v2\x17.proto.AgentInformationR\x10agentInformation\x12%\n" +
	"\aos_info\x18\x03 \x01(\v2\f.proto.UnameR\x06osInfo\x12 \n" +
	"\flast_seen_at\x18\a \x01(\x04R\n" +
	"lastSeenAt\x12\x17\n" +
	"\alast_ip\x18\x10 \x01(\tR\x06lastIp\x12\x16\n" +
	"\x06labels\x18\x12 \x03(\tR\x06labels\"w\n" +
	"\x11ArtifactParameter\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\adefault\x18\x02 \x01(\tR\adefault\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\"$\n" +
	"\x0eArtifactSource\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\"\xab\x01\n" +
	"\bArtifact\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x128\n" +
	"\n" +
	"parameters\x18\x03 \x03(\v2\x18.proto.ArtifactParameterR\n" +
	"parameters\x12/\n" +
	"\asources\x18\x04 \x03(\v2\x15.proto.ArtifactSourceR\asources\"x\n" +
	"\x13GetArtifactsRequest\x12\x1f\n" +
	"\vsearch_term\x18\x03 \x01(\tR\n" +
	"searchTerm\x12*\n" +
	"\x11number_of_results\x18\x04 \x01(\x04R\x0fnumberOfResults\x12\x14\n" +
	"\x05names\x18\x06 \x03(\tR\x05names\"<\n" +
	"\x13ArtifactDescriptors\x12%\n" +
	"\x05items\x18\x01 \x03(\v2\x0f.proto.ArtifactR\x05itemsBLZJgithub.com/hdyrawan/agentic-velociraptor-mcp/internal/velociraptor/veloapib\x06proto3"

var (
	file_visibility_proto_rawDescOnce sync.Once
	file_visibility_proto_rawDescData []byte
)

func file_visibility_proto_rawDescGZIP() []byte {
	file_visibility_proto_rawDescOnce.Do(func() {
		file_visibility_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_visibility_proto_rawDesc), len(file_visibility_proto_rawDesc)))
	})
	return file_visibility_proto_rawDescData
}

var file_visibility_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_visibility_proto_goTypes = []any{
	(*SearchClientsRequest)(nil),  // 0: proto.SearchClientsRequest
	(*SearchClientsResponse)(nil), // 1: proto.SearchClientsResponse
	(*GetClientRequest)(nil),      // 2: proto.GetClientRequest
	(*AgentInformation)(nil),      // 3: proto.AgentInformation
	(*Uname)(nil),                 // 4: proto.Uname
	(*ApiClient)(nil),             // 5: proto.ApiClient
	(*ArtifactParameter)(nil),     // 6: proto.ArtifactParameter
	(*ArtifactSource)(nil),        // 7: proto.ArtifactSource
	(*Artifact)(nil),              // 8: proto.Artifact
	(*GetArtifactsRequest)(nil),   // 9: proto.GetArtifactsRequest
	(*ArtifactDescriptors)(nil),   // 10: proto.ArtifactDescriptors
}
var file_visibility_proto_depIdxs = []int32{
	5, // 0: proto.SearchClientsResponse.items:type_name -> proto.ApiClient
	3, // 1: proto.ApiClient.agent_information:type_name -> proto.AgentInformation
	4, // 2: proto.ApiClient.os_info:type_name -> proto.Uname
	6, // 3: proto.Artifact.parameters:type_name -> proto.ArtifactParameter
	7, // 4: proto.Artifact.sources:type_name -> proto.ArtifactSource
	8, // 5: proto.ArtifactDescriptors.items:type_name -> proto.Artifact
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_visibility_proto_init() }
func file_visibility_proto_init() {
	if File_visibility_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_visibility_proto_rawDesc), len(file_visibility_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_visibility_proto_goTypes,
		DependencyIndexes: file_visibility_proto_depIdxs,
		MessageInfos:      file_visibility_proto_msgTypes,
	}.Build()
	File_visibility_proto = out.File
	file_visibility_proto_goTypes = nil
	file_visibility_proto_depIdxs = nil
}
