// Copyright 2026 hdyrawan
//
// Minimal mirror of actions/proto/vql.proto's VQLEnv message: a single
// key/value pair used to bind one artifact parameter. This is the only
// mechanism this project uses to pass a value into a collection or
// hunt — the value always lands in VQLEnv.value, a plain protobuf
// string field, never interpolated into a query string. See
// docs/security-model.md.
//
// Regenerate with (from the repository root):
//   buf generate internal/velociraptor/veloapi

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: vql.proto

package veloapi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VQLEnv struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VQLEnv) Reset() {
	*x = VQLEnv{}
	mi := &file_vql_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VQLEnv) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VQLEnv) ProtoMessage() {}

func (x *VQLEnv) ProtoReflect() protoreflect.Message {
	mi := &file_vql_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VQLEnv.ProtoReflect.Descriptor instead.
func (*VQLEnv) Descriptor() ([]byte, []int) {
	return file_vql_proto_rawDescGZIP(), []int{0}
}

func (x *VQLEnv) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *VQLEnv) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_vql_proto protoreflect.FileDescriptor

const file_vql_proto_rawDesc = "" +
	"\n" +
	"\tvql.proto\x12\x05proto\"0\n" +
	"\x06VQLEnv\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05valueBLZJgithub.com/hdyrawan/agentic-velociraptor-mcp/internal/velociraptor/veloapib\x06proto3"

var (
	file_vql_proto_rawDescOnce sync.Once
	file_vql_proto_rawDescData []byte
)

func file_vql_proto_rawDescGZIP() []byte {
	file_vql_proto_rawDescOnce.Do(func() {
		file_vql_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_vql_proto_rawDesc), len(file_vql_proto_rawDesc)))
	})
	return file_vql_proto_rawDescData
}

var file_vql_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_vql_proto_goTypes = []any{
	(*VQLEnv)(nil), // 0: proto.VQLEnv
}
var file_vql_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_vql_proto_init() }
func file_vql_proto_init() {
	if File_vql_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_vql_proto_rawDesc), len(file_vql_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_vql_proto_goTypes,
		DependencyIndexes: file_vql_proto_depIdxs,
		MessageInfos:      file_vql_proto_msgTypes,
	}.Build()
	File_vql_proto = out.File
	file_vql_proto_goTypes = nil
	file_vql_proto_depIdxs = nil
}
